mutation CreateReservation($request: ReservationRequestInput!) {
  reservation: createReservation(reservationRequest: $request) {
    ... on ReservationInfo {
      id
      name
      size
      restrictions
      restaurant {
        id
        name
      }
      tables {
        size
        quantity
      }
      reservationTime
      createdTime
      updatedTime
      active
    }
    ... on ReservationError {
      error
      message
    }
  }
}