mutation DeleteReservation($id: String!) {
  reservation: deleteReservation(id: $id) {
    ... on ReservationInfo {
      name
      size
      reservationTime
    }
    ... on ReservationError {
      error
      message
    }
  }
}