query FindTable(
  $time: DateTime!,
  $size: Int!,
  $endorsements: [Endorsement]!,
) {
  restaurants: findTable(
    time: $time,
    size: $size,
    endorsements: $endorsements
  ) {
    id
    name
    size
    endorsements
    tables {
      size
      quantity
    }
    occupiedTables {
      size
      quantity
    }
    availableTables {
      size
      quantity
    }
  }
}