query FindRestaurantsWithEndorsements(
  $endorsements: [Endorsement!]!,
) {
  restaurants: findRestaurantWithEndorsements(
    endorsements: $endorsements
  ) {
    id
    name
    endorsements
    tables {
      size
      quantity
    }
  }
}
