query GetReservation($id: String!) {
  reservation: reservation(id: $id) {
    id
    name
    size
    restrictions
    restaurant {
      id
      name
    }
    tables {
      size
      quantity
    }
    reservationTime
    createdTime
    updatedTime
    active
  }
}
